# Generated by Django 3.2.10 on 2022-05-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='pwd',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='文章密码'),
        ),
    ]
