# Generated by Django 3.2.10 on 2022-05-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_articles_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='word',
            field=models.IntegerField(default=0, verbose_name='文章字数'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, '前端'), (2, '后端')], null=True, verbose_name='文章分类'),
        ),
    ]
