# Generated by Django 3.2.10 on 2022-05-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220515_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='moods',
            name='addr',
            field=models.JSONField(null=True, verbose_name='用户地址信息'),
        ),
        migrations.AddField(
            model_name='moods',
            name='ip',
            field=models.GenericIPAddressField(default='171.120.159.122', verbose_name='ip地址'),
        ),
    ]
